name: Resource Deployment Apply

on: 
 push:
  branches:
   - main
  paths:
   - ".github/workflows/pim-apply.yml"
   - "deployment/**"

permissions:
  id-token: write
  contents: read

jobs:
 Deployment:
   name: Terraform Apply Plan
   uses: NizamORG/Terraform-reusable/.github/workflows/terraform-apply.yml@main
   secrets: inherit
   with:
    workingDirectory: ./Deployment