name: Resource Deployment Apply

on: 
 push:
  branches:
   - main
  paths:
   - ".github/workflows/pim-apply.yml"
   - "deployment/**"

permissions:
  id-token: write
  contents: read

jobs:
  Group-Deployment:
    name: Terraform Apply Plan
    uses: NizamORG/Terraform-reusable/.github/workflows/terraform-apply.yml@main
    secrets: inherit
    with:
      workingDirectory: ./deployment
      terraformArgs: "-target=module.aad_groups_final.module.aad_groups"
  Role-Assignment:
    needs: Group-Deployment
    name: Terraform Apply Plan
    uses: NizamORG/Terraform-reusable/.github/workflows/terraform-apply.yml@main
    secrets: inherit
    with:
      workingDirectory: ./deployment
      terraformArgs: "-target=module.aad_groups_final.module.aad_role"